config/routes.rb
LoadMore::Application.routes.draw do
  root 'users#index'
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
	default_scope { order('id ASC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    if params[:id]
      @users = User.where('id >?', params[:id]).limit(1).where('code > ?', '100200')
    else
      @users = User.where('code > ?', '100200').limit(1)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CSE 5335 Project 2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>





<body>
<%= yield %>

</body>
</html>

app/views/users/_user.html.erb
 <div class="slide-left"> 
  <div class="record" data-id="<%= user.id %>">
    <b>Ranking: </b> <%= user.id %>
    <b>University Code: </b> <%= user.code %>
    <b>University Name: </b> <%= user.name %>
    <b>Location: </b> <%= user.location %> 
  </div>
  </div>
 

app/views/users/index.html.erb
<div class="container">
  
</div>
<div class="lmc">
	<%= link_to "Start Loading", users_path, class: "button" %>
</div>

app/views/users/index.js.erb
if (myFuncCalls == 21){
         $('.container').html('<%= escape_javascript(render(:partial => @users)) %>');
         myFuncCalls = 0;
}
else {
	$('.container').append('<%= escape_javascript(render(:partial => @users)) %>');
	myFuncCalls++;
}